"""initial schema

Revision ID: a9ed48e7c8d4
Revises: 
Create Date: 2026-09-15 05:28:06.739459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ed48e7c8d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_table('backtests',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('risk_per_trade_percent', sa.Float(), nullable=False),
    sa.Column('slippage_bps', sa.Float(), nullable=False),
    sa.Column('commission_bps', sa.Float(), nullable=False),
    sa.Column('total_return_percent', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('profit_factor', sa.Float(), nullable=False),
    sa.Column('max_drawdown_percent', sa.Float(), nullable=False),
    sa.Column('sharpe_like', sa.Float(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('average_trade_percent', sa.Float(), nullable=False),
    sa.Column('expectancy', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtests_completed_at'), 'backtests', ['completed_at'], unique=False)
    op.create_index(op.f('ix_backtests_symbol'), 'backtests', ['symbol'], unique=False)
    op.create_table('instruments',
    sa.Column('canonical_symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('digits', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=True),
    sa.Column('quote_currency', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('canonical_symbol')
    )
    op.create_table('market_candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candles_symbol_tf_time', 'market_candles', ['symbol', 'timeframe', 'time'], unique=True)
    op.create_table('market_quotes',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('change_percent', sa.Float(), nullable=False),
    sa.Column('change_absolute', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('spark', sa.String(length=2000), nullable=False),
    sa.Column('freshness', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('performance_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('drawdown_percent', sa.Float(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_snapshots_as_of'), 'performance_snapshots', ['as_of'], unique=False)
    op.create_table('quant_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('quant_score', sa.Float(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('trend_direction', sa.String(length=20), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=False),
    sa.Column('momentum_direction', sa.String(length=20), nullable=False),
    sa.Column('volatility_score', sa.Float(), nullable=False),
    sa.Column('volatility_regime', sa.String(length=20), nullable=False),
    sa.Column('structure_score', sa.Float(), nullable=False),
    sa.Column('structure_direction', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quant_snapshots_symbol'), 'quant_snapshots', ['symbol'], unique=False)
    op.create_table('sentiment_observations',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entities', sa.String(length=500), nullable=False),
    sa.Column('raw_sentiment_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_observations_published_at'), 'sentiment_observations', ['published_at'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('quant_score', sa.Float(), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('narrative', sa.String(length=2000), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_generated_at'), 'signals', ['generated_at'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('backtest_id', sa.String(length=80), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('pnl_percent', sa.Float(), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_backtest_id'), 'backtest_trades', ['backtest_id'], unique=False)
    op.create_index(op.f('ix_backtest_trades_symbol'), 'backtest_trades', ['symbol'], unique=False)
    op.create_table('signal_factors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.String(length=80), nullable=False),
    sa.Column('factor_id', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_label', sa.String(length=40), nullable=False),
    sa.Column('explanation', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.String(length=80), nullable=False),
    sa.Column('entry_low', sa.Float(), nullable=False),
    sa.Column('entry_high', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_plans')
    op.drop_table('signal_factors')
    op.drop_index(op.f('ix_backtest_trades_symbol'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_backtest_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_generated_at'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_sentiment_observations_published_at'), table_name='sentiment_observations')
    op.drop_table('sentiment_observations')
    op.drop_index(op.f('ix_quant_snapshots_symbol'), table_name='quant_snapshots')
    op.drop_table('quant_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_as_of'), table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    op.drop_table('market_quotes')
    op.drop_index('ix_candles_symbol_tf_time', table_name='market_candles')
    op.drop_table('market_candles')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_backtests_symbol'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_completed_at'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
